project_name: spire-gcpsecret-plugin

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/server/upstreamauthority_gcp_secret
    binary: upstreamauthority_gcp_secret
    env: [ CGO_ENABLED=0 ]
    goos:
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - '--yes'
    artifacts: checksum

archives:
  - format: binary
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}'

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - '^docs'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999